/**
 * Blog posts metadata for SSG.
 * Full content lives in the individual page components.
 * Images should be placed in /public/blog/ folder.
 * Sorted: newest → oldest, prioritized by marketing & sales value.
 */
export const BLOG_POSTS = [
  {
    id: 20,
    slug: 'שיווק-בוואטסאפ-מדריך-מלא-לעסקים-2026',
    slugEn: 'whatsapp-marketing-complete-guide-for-businesses-2026',
    title: { he: 'שיווק בוואטסאפ — המדריך המלא לעסקים בישראל 2026', en: 'WhatsApp Marketing — Complete Guide for Businesses 2026' },
    description: { he: 'איך לשווק נכון בוואטסאפ — אסטרטגיות, תבניות, סגמנטציה ומדידה. כל מה שצריך לדעת על שיווק בוואטסאפ בעידן ה-API.', en: 'How to market effectively on WhatsApp — strategies, templates, segmentation and measurement. Everything you need to know about WhatsApp marketing in the API era.' },
    seoTitle: { he: 'שיווק בוואטסאפ | מדריך מלא 2026 | גמבוט', en: 'WhatsApp Marketing Guide 2026 | Gambot' },
    metaDescription: { he: 'מדריך שיווק בוואטסאפ לעסקים ✓ אסטרטגיות ✓ קמפיינים ✓ תבניות ✓ מדידה. הגדלת המרות עם WhatsApp API.', en: 'WhatsApp marketing guide for businesses ✓ Strategies ✓ Campaigns ✓ Templates ✓ Measurement. Increase conversions with WhatsApp API.' },
    keywords: { he: 'שיווק בוואטסאפ, whatsapp marketing, קמפיין וואטסאפ, שיווק דיגיטלי', en: 'whatsapp marketing, whatsapp campaign, digital marketing, whatsapp promotions' },
    category: 'Marketing',
    author: 'ניר סגס',
    publishedDate: '2026-03-14',
    image: '/blog/post20.jpg',
    readTime: 10,
  },
  {
    id: 21,
    slug: 'ניהול-לידים-בוואטסאפ',
    slugEn: 'whatsapp-lead-management-guide',
    title: { he: 'ניהול לידים בוואטסאפ — איך להפוך שיחות ללקוחות משלמים', en: 'WhatsApp Lead Management — How to Convert Conversations to Paying Customers' },
    description: { he: 'מדריך מקיף לניהול לידים בוואטסאפ — קליטת לידים, מיון, מעקב ואוטומציה. הגדל שיעור ההמרה שלך עם גמבוט.', en: 'Comprehensive guide to WhatsApp lead management — lead capture, qualification, follow-up and automation. Increase your conversion rate with Gambot.' },
    seoTitle: { he: 'ניהול לידים בוואטסאפ | מדריך 2026 | גמבוט', en: 'WhatsApp Lead Management Guide 2026 | Gambot' },
    metaDescription: { he: 'ניהול לידים חכם בוואטסאפ ✓ קליטה אוטומטית ✓ מיון לידים ✓ follow-up אוטומטי ✓ סגירת עסקאות. עם גמבוט.', en: 'Smart WhatsApp lead management ✓ Automatic capture ✓ Lead scoring ✓ Automated follow-up ✓ Deal closing. With Gambot.' },
    keywords: { he: 'ניהול לידים וואטסאפ, lead management, המרת לידים, sales automation', en: 'whatsapp lead management, lead capture, lead scoring, sales automation' },
    category: 'Sales',
    author: 'ניר סגס',
    publishedDate: '2026-03-10',
    image: '/blog/post21.jpg',
    readTime: 9,
  },
  {
    id: 7,
    slug: 'כיצד-להגדיל-מכירות-עם-וואטסאפ',
    slugEn: 'how-to-increase-sales-with-whatsapp',
    title: { he: 'כיצד להגדיל מכירות עם וואטסאפ — 10 אסטרטגיות מוכחות', en: 'How to Increase Sales with WhatsApp — 10 Proven Strategies' },
    description: { he: '10 אסטרטגיות מוכחות להגדלת מכירות עם וואטסאפ — מניהול לידים ועד סגירת עסקאות, עם דוגמאות אמיתיות.', en: '10 proven strategies to increase sales with WhatsApp — from lead management to closing deals with real examples.' },
    seoTitle: { he: 'להגדיל מכירות עם וואטסאפ | 10 אסטרטגיות 2026', en: 'Increase Sales with WhatsApp | 10 Strategies 2026' },
    metaDescription: { he: '10 אסטרטגיות להגדלת מכירות עם וואטסאפ בעסק שלך. ניהול לידים, follow-up, שיחות מכירה ועוד.', en: '10 strategies to boost sales with WhatsApp for your business. Lead management, follow-up, sales conversations and more.' },
    keywords: { he: 'מכירות וואטסאפ, sales whatsapp, ניהול לידים, sales bot', en: 'whatsapp sales, lead management, sales bot, increase revenue' },
    category: 'Sales',
    author: 'ניר סגס',
    publishedDate: '2026-03-06',
    image: '/blog/post7.jpg',
    readTime: 9,
  },
  {
    id: 24,
    slug: 'הצעות-מחיר-דיגיטליות-בוואטסאפ',
    slugEn: 'digital-quotes-on-whatsapp',
    title: { he: 'הצעות מחיר דיגיטליות בוואטסאפ — שלחו, עקבו וסגרו עסקאות', en: 'Digital Quotes on WhatsApp — Send, Track and Close Deals' },
    description: { he: 'כיצד לשלוח הצעות מחיר מקצועיות בוואטסאפ — עיצוב, מעקב, חתימה ואוטומציה. הגדל את שיעור הסגירה.', en: 'How to send professional quotes on WhatsApp — design, tracking, signing and automation. Increase your close rate.' },
    seoTitle: { he: 'הצעות מחיר בוואטסאפ | מדריך 2026 | גמבוט', en: 'Digital Quotes on WhatsApp | Guide 2026 | Gambot' },
    metaDescription: { he: 'שלחו הצעות מחיר דיגיטליות בוואטסאפ ✓ עיצוב מקצועי ✓ מעקב פתיחות ✓ חתימה דיגיטלית. עם גמבוט.', en: 'Send digital quotes on WhatsApp ✓ Professional design ✓ Open tracking ✓ Digital signature. With Gambot.' },
    keywords: { he: 'הצעת מחיר דיגיטלית, הצעות מחיר וואטסאפ, digital quote, sales proposal', en: 'digital quote whatsapp, sales proposal, quote tracking, close deals whatsapp' },
    category: 'Sales',
    author: 'ניר סגס',
    publishedDate: '2026-03-01',
    image: '/blog/post24.jpg',
    readTime: 8,
  },
  {
    id: 19,
    slug: 'איך-בונים-בוט-לוואטסאפ-עם-גמבוט',
    slugEn: 'how-to-build-a-whatsapp-bot-with-gambot',
    title: { he: 'איך בונים בוט לוואטסאפ עם גמבוט — מדריך מלא 2026', en: 'How to Build a WhatsApp Bot with Gambot — Complete Guide 2026' },
    description: { he: 'מדריך מפורט לבניית בוט לוואטסאפ עם גמבוט — מהודעת פתיחה ועד ניתוב לנציגים, ניהול לידים ושילוב AI. צעד אחר צעד עם Bot Builder.', en: 'Detailed guide to building a WhatsApp bot with Gambot — from welcome message to agent routing, lead management and AI integration. Step by step with Bot Builder.' },
    seoTitle: { he: 'איך בונים בוט לוואטסאפ | מדריך מלא 2026 | גמבוט Bot Builder', en: 'How to Build a WhatsApp Bot | Complete Guide 2026 | Gambot Bot Builder' },
    metaDescription: { he: 'בנו בוט לוואטסאפ ב-5 צעדים פשוטים עם גמבוט ✓ ניתוב מכירות שירות שיווק ✓ תור עבודה לנציגים ✓ ניהול לידים ✓ שילוב AI — ללא קוד', en: 'Build a WhatsApp bot in 5 simple steps with Gambot ✓ Sales service marketing routing ✓ Agent work queue ✓ Lead management ✓ AI integration — no code' },
    keywords: { he: 'בוט לוואטסאפ, איך בונים בוט לוואטסאפ, בוט וואטסאפ מחיר, bot builder, gambot, בוט whatsapp, בניית בוט, בוט לעסקים', en: 'whatsapp bot, how to build whatsapp bot, whatsapp bot price, bot builder, gambot, build bot, business bot' },
    category: 'Tutorial',
    author: 'ניר סגס',
    publishedDate: '2026-02-24',
    image: '/blog/post19.jpg',
    readTime: 12,
  },
  {
    id: 8,
    slug: 'קמפיינים-שיווקיים-בוואטסאפ-מדריך-מלא',
    slugEn: 'whatsapp-marketing-campaigns-complete-guide',
    title: { he: 'קמפיינים שיווקיים בוואטסאפ — מדריך מלא לשנת 2026', en: 'WhatsApp Marketing Campaigns — Complete Guide 2026' },
    description: { he: 'מדריך מלא לניהול קמפיינים שיווקיים בוואטסאפ — תכנון, יצירת תבניות, סגמנטציה, שליחה ומדידה.', en: 'Complete guide to managing WhatsApp marketing campaigns — planning, template creation, segmentation, sending and measurement.' },
    seoTitle: { he: 'קמפיינים שיווקיים בוואטסאפ | מדריך מלא 2026 | גמבוט', en: 'WhatsApp Marketing Campaigns | Complete Guide 2026 | Gambot' },
    metaDescription: { he: 'מדריך מלא לקמפיינים שיווקיים בוואטסאפ. תכנון, תבניות, סגמנטציה, שליחה ומדידה. הגדילו המרות ב-40%.', en: 'Complete guide to WhatsApp marketing campaigns. Planning, templates, segmentation, sending and measurement. Increase conversions by 40%.' },
    keywords: { he: 'קמפיין וואטסאפ, שיווק בוואטסאפ, WhatsApp marketing, bulk messaging', en: 'whatsapp campaign, whatsapp marketing, bulk messaging, marketing automation' },
    category: 'Marketing',
    author: 'ניר סגס',
    publishedDate: '2026-02-18',
    image: '/blog/post8.jpg',
    readTime: 11,
  },
  {
    id: 12,
    slug: 'אוטומציה-שיווקית-בוואטסאפ',
    slugEn: 'marketing-automation-whatsapp',
    title: { he: 'אוטומציה שיווקית בוואטסאפ — מדריך מלא לשנת 2026', en: 'Marketing Automation on WhatsApp — Complete Guide 2026' },
    description: { he: 'כיצד לבנות אוטומציה שיווקית בוואטסאפ — תהליכי nurturing, re-engagement, drip campaigns ועוד.', en: 'How to build marketing automation on WhatsApp — nurturing flows, re-engagement, drip campaigns and more.' },
    seoTitle: { he: 'אוטומציה שיווקית בוואטסאפ | מדריך מלא 2026 | גמבוט', en: 'WhatsApp Marketing Automation | Complete Guide 2026 | Gambot' },
    metaDescription: { he: 'בנו אוטומציה שיווקית בוואטסאפ. drip campaigns, re-engagement, nurturing ועוד. הגדילו ROI.', en: 'Build WhatsApp marketing automation. Drip campaigns, re-engagement, nurturing and more. Increase ROI.' },
    keywords: { he: 'אוטומציה שיווקית וואטסאפ, drip campaign, marketing automation, nurturing', en: 'whatsapp marketing automation, drip campaign, nurturing, re-engagement' },
    category: 'Marketing Automation',
    author: 'ניר סגס',
    publishedDate: '2026-02-12',
    image: '/blog/post12.jpg',
    readTime: 9,
  },
  {
    id: 23,
    slug: 'crm-לוואטסאפ-ניהול-לקוחות-חכם',
    slugEn: 'whatsapp-crm-smart-customer-management',
    title: { he: 'CRM לוואטסאפ — ניהול לקוחות חכם ישירות בצ\'אט', en: 'WhatsApp CRM — Smart Customer Management Directly in Chat' },
    description: { he: 'כיצד לנהל CRM מלא ישירות בוואטסאפ — היסטוריית שיחות, תגיות, משימות ואינטגרציה עם מערכות קיימות.', en: 'How to manage a full CRM directly in WhatsApp — conversation history, tags, tasks and integration with existing systems.' },
    seoTitle: { he: 'CRM לוואטסאפ | ניהול לקוחות | מדריך 2026 | גמבוט', en: 'WhatsApp CRM | Customer Management | Guide 2026 | Gambot' },
    metaDescription: { he: 'CRM בוואטסאפ ✓ היסטוריית שיחות ✓ תגיות ✓ משימות ✓ אינטגרציה עם Salesforce, HubSpot ועוד. עם גמבוט.', en: 'WhatsApp CRM ✓ Conversation history ✓ Tags ✓ Tasks ✓ Integration with Salesforce, HubSpot and more. With Gambot.' },
    keywords: { he: 'crm וואטסאפ, whatsapp crm, ניהול לקוחות, אינטגרציה crm', en: 'whatsapp crm, customer management whatsapp, crm integration, whatsapp salesforce' },
    category: 'CRM',
    author: 'ניר סגס',
    publishedDate: '2026-02-06',
    image: '/blog/post23.jpg',
    readTime: 8,
  },
  {
    id: 22,
    slug: 'חתימה-דיגיטלית-בוואטסאפ',
    slugEn: 'digital-signature-on-whatsapp',
    title: { he: 'חתימה דיגיטלית בוואטסאפ — חתמו על מסמכים בשניות', en: 'Digital Signature on WhatsApp — Sign Documents in Seconds' },
    description: { he: 'כיצד לשלוח ולקבל חתימות דיגיטליות דרך וואטסאפ — חוזים, הצעות מחיר ואישורים. חוסך זמן ומגדיל המרות.', en: 'How to send and receive digital signatures via WhatsApp — contracts, quotes and approvals. Saves time and increases conversions.' },
    seoTitle: { he: 'חתימה דיגיטלית בוואטסאפ | מדריך 2026 | גמבוט', en: 'Digital Signature on WhatsApp | Guide 2026 | Gambot' },
    metaDescription: { he: 'חתימה דיגיטלית בוואטסאפ ✓ חוזים ✓ הצעות מחיר ✓ אישורים — חתמו בשניות ישירות בצ\'אט. עם גמבוט.', en: 'Digital signature on WhatsApp ✓ Contracts ✓ Quotes ✓ Approvals — sign in seconds directly in chat. With Gambot.' },
    keywords: { he: 'חתימה דיגיטלית, חתימה וואטסאפ, digital signature, חוזה אונליין', en: 'digital signature whatsapp, online signature, contract signing, document signing' },
    category: 'Productivity',
    author: 'ניר סגס',
    publishedDate: '2026-01-30',
    image: '/blog/post22.jpg',
    readTime: 7,
  },
  {
    id: 27,
    slug: 'שירות-לקוחות-בוואטסאפ-מדריך-מלא',
    slugEn: 'whatsapp-customer-service-complete-guide',
    title: { he: 'שירות לקוחות בוואטסאפ — המדריך המלא לעסקים 2026', en: 'WhatsApp Customer Service — Complete Business Guide 2026' },
    description: { he: 'כיצד לבנות מערך שירות לקוחות מנצח בוואטסאפ — בוטים, נציגים, SLA, CSAT ועוד. הגדל שביעות רצון ב-40%.', en: 'How to build a winning customer service system on WhatsApp — bots, agents, SLA, CSAT and more. Increase satisfaction by 40%.' },
    seoTitle: { he: 'שירות לקוחות בוואטסאפ | מדריך מלא 2026 | גמבוט', en: 'WhatsApp Customer Service Guide 2026 | Gambot' },
    metaDescription: { he: 'שירות לקוחות בוואטסאפ ✓ בוטים חכמים ✓ SLA ✓ CSAT ✓ ניתוב אוטומטי. הגדל שביעות רצון ב-40%.', en: 'WhatsApp customer service ✓ Smart bots ✓ SLA ✓ CSAT ✓ Automatic routing. Increase satisfaction by 40%.' },
    keywords: { he: 'שירות לקוחות וואטסאפ, customer service bot, CSAT, whatsapp support', en: 'whatsapp customer service, support bot, CSAT, SLA whatsapp' },
    category: 'Customer Service',
    author: 'ניר סגס',
    publishedDate: '2026-01-22',
    image: '/blog/post27.jpg',
    readTime: 10,
  },
  {
    id: 25,
    slug: 'shared-inbox-לוואטסאפ',
    slugEn: 'whatsapp-shared-inbox-guide',
    title: { he: 'Shared Inbox לוואטסאפ — כל הצוות, מסך אחד, לקוח מרוצה', en: 'WhatsApp Shared Inbox — Whole Team, One Screen, Happy Customer' },
    description: { he: 'איך לנהל את כל שיחות הוואטסאפ של העסק עם צוות שלם — תור עבודה, הקצאה, SLA ומדדי ביצוע.', en: 'How to manage all your business WhatsApp conversations with a full team — work queue, assignment, SLA and performance metrics.' },
    seoTitle: { he: 'Shared Inbox וואטסאפ | ניהול צוות | מדריך 2026 | גמבוט', en: 'WhatsApp Shared Inbox | Team Management | Guide 2026 | Gambot' },
    metaDescription: { he: 'Shared Inbox לוואטסאפ ✓ ניהול צוות ✓ תור עבודה ✓ SLA ✓ מדדי ביצוע — ניהול שיחות יעיל. עם גמבוט.', en: 'WhatsApp Shared Inbox ✓ Team management ✓ Work queue ✓ SLA ✓ Performance metrics — efficient conversation management. With Gambot.' },
    keywords: { he: 'shared inbox וואטסאפ, whatsapp shared inbox, ניהול צוות, תור עבודה', en: 'whatsapp shared inbox, team inbox, whatsapp team management, customer queue' },
    category: 'Customer Service',
    author: 'ניר סגס',
    publishedDate: '2026-01-15',
    image: '/blog/post25.jpg',
    readTime: 9,
  },
  {
    id: 26,
    slug: 'תבניות-הודעה-לוואטסאפ',
    slugEn: 'whatsapp-message-templates-guide',
    title: { he: 'תבניות הודעה לוואטסאפ — איך ליצור תבניות שמניבות תוצאות', en: 'WhatsApp Message Templates — How to Create Templates That Drive Results' },
    description: { he: 'מדריך מקיף ליצירת תבניות הודעה ל-WhatsApp API — אישור מטא, best practices, וטיפים לשיפור ה-CTR.', en: 'Comprehensive guide to creating WhatsApp API message templates — Meta approval, best practices, and tips to improve CTR.' },
    seoTitle: { he: 'תבניות הודעה לוואטסאפ | מדריך 2026 | גמבוט', en: 'WhatsApp Message Templates Guide 2026 | Gambot' },
    metaDescription: { he: 'יצירת תבניות הודעה ל-WhatsApp API ✓ אישור מטא ✓ best practices ✓ שיפור CTR. מדריך מלא.', en: 'Creating WhatsApp API message templates ✓ Meta approval ✓ Best practices ✓ Improve CTR. Complete guide.' },
    keywords: { he: 'תבניות הודעה וואטסאפ, whatsapp templates, message template, אישור מטא', en: 'whatsapp message templates, template approval, whatsapp api templates, CTR' },
    category: 'Best Practices',
    author: 'ניר סגס',
    publishedDate: '2026-01-08',
    image: '/blog/post26.jpg',
    readTime: 8,
  },
  {
    id: 32,
    slug: 'whatsapp-api-מול-whatsapp-business-app',
    slugEn: 'whatsapp-api-vs-whatsapp-business-app-full-comparison',
    title: { he: 'WhatsApp API מול WhatsApp Business App — השוואה מלאה 2026', en: 'WhatsApp API vs WhatsApp Business App — Full Comparison 2026' },
    description: { he: 'השוואה מעמיקה בין WhatsApp API ל-WhatsApp Business App — תכונות, מחירים, יכולות ולמי מתאים כל אחד.', en: 'In-depth comparison of WhatsApp API vs WhatsApp Business App — features, pricing, capabilities and who should use each.' },
    seoTitle: { he: 'WhatsApp API מול WhatsApp Business App | השוואה 2026 | גמבוט', en: 'WhatsApp API vs WhatsApp Business App | Full Comparison 2026 | Gambot' },
    metaDescription: { he: 'השוואה: WhatsApp API מול WhatsApp Business App ✓ תכונות ✓ מחירים ✓ יכולות ✓ מי צריך מה. מדריך 2026.', en: 'Comparison: WhatsApp API vs WhatsApp Business App ✓ Features ✓ Pricing ✓ Capabilities ✓ Who needs what. Guide 2026.' },
    keywords: { he: 'whatsapp api מול business, השוואה whatsapp, whatsapp business app, whatsapp api ישראל', en: 'whatsapp api vs business app, whatsapp comparison, choose whatsapp plan, whatsapp api features' },
    category: 'WhatsApp API',
    author: 'ניר סגס',
    publishedDate: '2026-01-02',
    image: '/blog/post32.jpg',
    readTime: 9,
  },
  {
    id: 31,
    slug: 'וואטסאפ-לחנויות-וקמעונאות',
    slugEn: 'whatsapp-for-retail-stores',
    title: { he: 'וואטסאפ לחנויות ורשתות קמעונאות — הגדל מכירות בקלות', en: 'WhatsApp for Retail Stores — Boost Sales Easily' },
    description: { he: 'כיצד חנויות ורשתות קמעונאות משתמשות בוואטסאפ לשירות לקוחות, קמפיינים ועדכוני הזמנות. גמבוט לקמעונאות.', en: 'How retail stores and chains use WhatsApp for customer service, campaigns and order updates. Gambot for retail.' },
    seoTitle: { he: 'וואטסאפ לקמעונאות | חנויות | גמבוט 2026', en: 'WhatsApp for Retail Stores | Gambot 2026' },
    metaDescription: { he: 'וואטסאפ לקמעונאות ✓ שירות לקוחות ✓ קמפיינים ✓ עדכוני הזמנות ✓ נאמנות לקוחות. עם גמבוט.', en: 'WhatsApp for retail ✓ Customer service ✓ Campaigns ✓ Order updates ✓ Customer loyalty. With Gambot.' },
    keywords: { he: 'וואטסאפ חנות, retail whatsapp, קמעונאות וואטסאפ, שירות לקוחות חנות', en: 'whatsapp retail, retail store bot, ecommerce whatsapp, order updates whatsapp' },
    category: 'Industry',
    author: 'ניר סגס',
    publishedDate: '2025-12-22',
    image: '/blog/post31.jpg',
    readTime: 8,
  },
  {
    id: 30,
    slug: 'קמפיינים-עונתיים-בוואטסאפ',
    slugEn: 'seasonal-whatsapp-campaigns',
    title: { he: 'קמפיינים עונתיים בוואטסאפ — פסח, ראש השנה, קיץ וחגים', en: 'Seasonal WhatsApp Campaigns — Holidays, Summer and Special Events' },
    description: { he: 'מדריך לתכנון וביצוע קמפיינים עונתיים בוואטסאפ — פסח, ראש השנה, בלאק פריידי, קיץ ועוד. תבניות, טיפים ואסטרטגיות.', en: 'Guide to planning and executing seasonal WhatsApp campaigns — Passover, Rosh Hashana, Black Friday, summer and more. Templates, tips and strategies.' },
    seoTitle: { he: 'קמפיינים עונתיים בוואטסאפ | פסח, חגים, בלאק פריידי | גמבוט', en: 'Seasonal WhatsApp Campaigns | Holidays, Black Friday | Gambot 2026' },
    metaDescription: { he: 'קמפיינים עונתיים בוואטסאפ ✓ פסח ✓ ראש השנה ✓ בלאק פריידי ✓ קיץ. תבניות מוכנות ואסטרטגיות.', en: 'Seasonal WhatsApp campaigns ✓ Passover ✓ Rosh Hashana ✓ Black Friday ✓ Summer. Ready templates and strategies.' },
    keywords: { he: 'קמפיין עונתי, קמפיין פסח, קמפיין חגים, בלאק פריידי וואטסאפ', en: 'seasonal whatsapp campaign, holiday campaign, black friday whatsapp, promotional campaign' },
    category: 'Marketing',
    author: 'ניר סגס',
    publishedDate: '2025-12-15',
    image: '/blog/post30.jpg',
    readTime: 9,
  },
  {
    id: 28,
    slug: 'וואטסאפ-לנדלן',
    slugEn: 'whatsapp-for-real-estate',
    title: { he: 'וואטסאפ לנדל"ן — איך סוכני נדל"ן סוגרים יותר עסקאות עם גמבוט', en: 'WhatsApp for Real Estate — How Agents Close More Deals with Gambot' },
    description: { he: 'איך סוכני נדל"ן ומשרדים משתמשים בוואטסאפ לניהול לידים, תיאום סיורים ומעקב אחר עסקאות. גמבוט לנדל"ן.', en: 'How real estate agents and offices use WhatsApp for lead management, tour scheduling and deal tracking. Gambot for real estate.' },
    seoTitle: { he: 'וואטסאפ לנדל"ן | סוכני נדל"ן | גמבוט 2026', en: 'WhatsApp for Real Estate Agents | Gambot 2026' },
    metaDescription: { he: 'וואטסאפ לנדל"ן ✓ ניהול לידים ✓ תיאום סיורים ✓ מעקב עסקאות ✓ בוט נדל"ן. עם גמבוט.', en: 'WhatsApp for real estate ✓ Lead management ✓ Tour scheduling ✓ Deal tracking ✓ Real estate bot. With Gambot.' },
    keywords: { he: 'וואטסאפ נדל"ן, real estate whatsapp, סוכן נדל"ן בוט, ניהול לידים נדל"ן', en: 'whatsapp real estate, real estate bot, property leads whatsapp, real estate crm' },
    category: 'Industry',
    author: 'ניר סגס',
    publishedDate: '2025-12-08',
    image: '/blog/post28.jpg',
    readTime: 8,
  },
  {
    id: 29,
    slug: 'וואטסאפ-לבריאות-ורפואה',
    slugEn: 'whatsapp-for-healthcare',
    title: { he: 'וואטסאפ לרפואה — תורים, תזכורות ושירות חולים דיגיטלי', en: 'WhatsApp for Healthcare — Appointments, Reminders and Digital Patient Service' },
    description: { he: 'כיצד מרפאות, קופות חולים ורופאים פרטיים משתמשים בוואטסאפ לניהול תורים, תזכורות ותקשורת עם מטופלים.', en: 'How clinics, HMOs and private doctors use WhatsApp for appointment management, reminders and patient communication.' },
    seoTitle: { he: 'וואטסאפ לרפואה | ניהול תורים | גמבוט 2026', en: 'WhatsApp for Healthcare | Appointment Management | Gambot 2026' },
    metaDescription: { he: 'וואטסאפ לרפואה ✓ ניהול תורים ✓ תזכורות ✓ שאלונים ✓ מסמכים — שירות חולים דיגיטלי. עם גמבוט.', en: 'WhatsApp for healthcare ✓ Appointment management ✓ Reminders ✓ Questionnaires ✓ Documents — digital patient service. With Gambot.' },
    keywords: { he: 'וואטסאפ רפואה, healthcare whatsapp, ניהול תורים, תזכורת תור', en: 'whatsapp healthcare, medical appointment whatsapp, patient communication, appointment reminder' },
    category: 'Industry',
    author: 'ניר סגס',
    publishedDate: '2025-12-01',
    image: '/blog/post29.jpg',
    readTime: 8,
  },
  {
    id: 9,
    slug: 'ai-בוואטסאפ-מדריך-לעסקים',
    slugEn: 'ai-on-whatsapp-guide-for-businesses',
    title: { he: 'AI בוואטסאפ — מדריך לעסקים שרוצים להישאר קדימה', en: 'AI on WhatsApp — Guide for Businesses That Want to Stay Ahead' },
    description: { he: 'כיצד ליישם AI בוואטסאפ — chatbot AI, ניתוח שיחות, המלצות אוטומטיות ועוד. עתיד העסקים הוא כאן.', en: 'How to implement AI on WhatsApp — AI chatbot, conversation analysis, automated recommendations and more.' },
    seoTitle: { he: 'AI בוואטסאפ לעסקים | Gambot AI | מדריך 2026', en: 'AI on WhatsApp for Business | Gambot AI Guide 2026' },
    metaDescription: { he: 'יישום AI בוואטסאפ לעסק שלך. Chatbot AI, ניתוח שיחות, כוונות ותגובות חכמות. העתיד כבר כאן.', en: 'Implement AI on WhatsApp for your business. AI chatbot, conversation analysis, smart intent detection.' },
    keywords: { he: 'ai וואטסאפ, chatbot ai, בינה מלאכותית וואטסאפ, gambot ai', en: 'ai whatsapp, ai chatbot, whatsapp artificial intelligence, gambot ai' },
    category: 'AI & Technology',
    author: 'ניר סגס',
    publishedDate: '2025-11-20',
    image: '/blog/post9.jpg',
    readTime: 8,
  },
  {
    id: 11,
    slug: 'whatsapp-api-vs-whatsapp-business',
    slugEn: 'whatsapp-api-vs-whatsapp-business',
    title: { he: 'WhatsApp API לעומת WhatsApp Business — מה ההבדל?', en: 'WhatsApp API vs WhatsApp Business — What\'s the Difference?' },
    description: { he: 'השוואה מקיפה בין WhatsApp API ל-WhatsApp Business — תכונות, מחירים, מגבלות וכיצד לבחור.', en: 'Comprehensive comparison of WhatsApp API vs WhatsApp Business — features, pricing, limitations and how to choose.' },
    seoTitle: { he: 'WhatsApp API לעומת WhatsApp Business | השוואה 2026', en: 'WhatsApp API vs WhatsApp Business App | Comparison 2026' },
    metaDescription: { he: 'השוואה מלאה: WhatsApp API לעומת WhatsApp Business. תכונות, מחירים, מגבלות ומה מתאים לעסק שלך.', en: 'Full comparison: WhatsApp API vs WhatsApp Business. Features, pricing, limitations and which suits your business.' },
    keywords: { he: 'whatsapp api vs business, השוואה whatsapp, whatsapp business api, whatsapp לעסקים', en: 'whatsapp api vs business, whatsapp comparison, choose whatsapp plan' },
    category: 'WhatsApp API',
    author: 'ניר סגס',
    publishedDate: '2025-11-05',
    image: '/blog/post11.jpg',
    readTime: 7,
  },
  {
    id: 14,
    slug: 'איך-להגדיל-מספר-הודעות-בוואטסאפ-api',
    slugEn: 'how-to-increase-whatsapp-api-messaging-limits',
    title: { he: 'איך להגדיל את מספר ההודעות שניתן לשלוח ב-WhatsApp API', en: 'How to Increase WhatsApp API Messaging Limits' },
    description: { he: 'מדריך מלא להגדלת מגבלות ה-messaging ב-WhatsApp Business API — Quality Rating, Tier upgrade ועוד.', en: 'Complete guide to increasing WhatsApp Business API messaging limits — Quality Rating, Tier upgrade and more.' },
    seoTitle: { he: 'הגדלת מגבלות הודעות WhatsApp API | מדריך 2026', en: 'Increase WhatsApp API Messaging Limits | Guide 2026' },
    metaDescription: { he: 'כיצד להגדיל את מגבלות ה-messaging ב-WhatsApp API. Quality Rating, Tier upgrade, best practices.', en: 'How to increase WhatsApp API messaging limits. Quality Rating, Tier upgrade, best practices.' },
    keywords: { he: 'הגדלת מגבלות וואטסאפ, whatsapp tier, quality rating, whatsapp limits', en: 'whatsapp messaging limits, tier upgrade, quality rating, increase limit' },
    category: 'Technical',
    author: 'ניר סגס',
    publishedDate: '2025-10-20',
    image: '/blog/post14.jpg',
    readTime: 8,
  },
  {
    id: 6,
    slug: 'שירות-לקוחות-24-7-בוואטסאפ',
    slugEn: 'customer-service-24-7-whatsapp',
    title: { he: 'שירות לקוחות 24/7 בוואטסאפ — מדריך מלא', en: '24/7 Customer Service via WhatsApp — Complete Guide' },
    description: { he: 'כיצד לבנות שירות לקוחות 24/7 בוואטסאפ עם בוטים, ניתוב חכם ואינטגרציות. הגדילו CSAT והפחיתו עלויות.', en: 'How to build 24/7 customer service on WhatsApp with bots, smart routing and integrations. Increase CSAT and reduce costs.' },
    seoTitle: { he: 'שירות לקוחות 24/7 בוואטסאפ | מדריך 2026 | גמבוט', en: 'WhatsApp 24/7 Customer Service Guide 2026 | Gambot' },
    metaDescription: { he: 'בנו שירות לקוחות אוטומטי 24/7 בוואטסאפ. בוטים חכמים, ניתוב פניות, SLA ועוד. שפרו CSAT ב-40%.', en: 'Build automated 24/7 customer service on WhatsApp. Smart bots, routing, SLA and more. Improve CSAT by 40%.' },
    keywords: { he: 'שירות לקוחות וואטסאפ, customer service bot, CSAT, תמיכה אוטומטית', en: 'whatsapp customer service, support bot, CSAT, automated support' },
    category: 'Customer Service',
    author: 'ניר סגס',
    publishedDate: '2025-10-05',
    image: '/blog/post6.jpg',
    readTime: 7,
  },
  {
    id: 4,
    slug: 'איך-להגדיר-אוטומציה-בוואטסאפ',
    slugEn: 'how-to-set-up-whatsapp-automation',
    title: { he: 'איך להגדיר אוטומציה בוואטסאפ — Botomation מתחילים ועד מתקדמים', en: 'How to Set Up WhatsApp Automation — Botomation from Beginner to Advanced' },
    description: { he: 'מדריך מקיף לאוטומציה בוואטסאפ עם Botomation — טריגרים, תנאים, API, CRM ועוד. לכל רמות הניסיון.', en: 'Comprehensive guide to WhatsApp automation with Botomation — triggers, conditions, API, CRM and more for all levels.' },
    seoTitle: { he: 'אוטומציה בוואטסאפ | Botomation מדריך מלא 2026', en: 'WhatsApp Automation | Botomation Complete Guide 2026' },
    metaDescription: { he: 'מדריך מלא לאוטומציה בוואטסאפ עם Botomation. טריגרים, תנאים, API calls, Google Sheets, CRM ועוד.', en: 'Complete guide to WhatsApp automation with Botomation. Triggers, conditions, API calls, Google Sheets, CRM and more.' },
    keywords: { he: 'אוטומציה וואטסאפ, botomation, workflow אוטומטי, gambot automation', en: 'whatsapp automation, botomation, automated workflow, gambot' },
    category: 'Automation',
    author: 'ניר סגס',
    publishedDate: '2025-09-18',
    image: '/blog/post4.jpg',
    readTime: 12,
  },
  {
    id: 3,
    slug: 'איך-לבנות-בוט-ai-לוואטסאפ',
    slugEn: 'how-to-build-ai-bot-for-whatsapp',
    title: { he: 'איך לבנות בוט AI לוואטסאפ — מדריך צעד אחר צעד', en: 'How to Build an AI Bot for WhatsApp — Step by Step Guide' },
    description: { he: 'מדריך מפורט לבניית בוט AI לוואטסאפ עם Gambot — ללא קוד. מטריגרים ועד אקשנס, מ-AI ועד אינטגרציות.', en: 'Detailed guide to building an AI WhatsApp bot with Gambot — no code. From triggers to actions, AI to integrations.' },
    seoTitle: { he: 'איך לבנות בוט AI לוואטסאפ | מדריך מלא | גמבוט 2026', en: 'How to Build AI WhatsApp Bot | Complete Guide | Gambot 2026' },
    metaDescription: { he: 'צעד אחר צעד: בניית בוט AI לוואטסאפ עם Workflow Designer. טריגרים, אקשנס, AI, אינטגרציות — הכל ללא קוד.', en: 'Step by step: Build an AI WhatsApp bot with Workflow Designer. Triggers, actions, AI, integrations — all without code.' },
    keywords: { he: 'בוט ai וואטסאפ, בניית בוט, workflow designer, gambot tutorial', en: 'ai whatsapp bot, build bot, workflow designer, gambot tutorial' },
    category: 'Tutorial',
    author: 'ניר סגס',
    publishedDate: '2025-09-05',
    image: '/blog/post3.jpg',
    readTime: 10,
  },
  {
    id: 2,
    slug: 'שימושים-נפוצים-ב-whatsapp-business-api',
    slugEn: 'common-uses-of-whatsapp-business-api',
    title: { he: 'שימושים נפוצים ב-WhatsApp Business API', en: 'Common Uses of WhatsApp Business API' },
    description: { he: 'גלה את השימושים הנפוצים ביותר ב-WhatsApp Business API — מאוטומציה ועד שירות לקוחות. מקרי שימוש אמיתיים.', en: 'Discover the most common uses of WhatsApp Business API — from automation to customer service with real use cases.' },
    seoTitle: { he: 'שימושים נפוצים ב-WhatsApp API לעסקים | מדריך 2026', en: 'Common WhatsApp Business API Uses | Complete Guide 2026' },
    metaDescription: { he: 'שימושים מובילים ב-WhatsApp Business API לעסקים בישראל - אוטומציה, שיווק, שירות לקוחות ועוד. מקרי שימוש עם דוגמאות.', en: 'Leading WhatsApp Business API uses for businesses - automation, marketing, customer service and more with real examples.' },
    keywords: { he: 'whatsapp business api שימושים, אוטומציה וואטסאפ, שיווק וואטסאפ, שירות לקוחות וואטסאפ', en: 'whatsapp business api uses, whatsapp automation, whatsapp marketing, customer service' },
    category: 'Best Practices',
    author: 'ניר סגס',
    publishedDate: '2025-08-20',
    image: '/blog/post2.jpg',
    readTime: 6,
  },
  {
    id: 1,
    slug: 'מה-זה-whatsapp-api-ואיך-הוא-משדרג-את-העסק-שלך',
    slugEn: 'what-is-whatsapp-api-and-how-does-it-upgrade-your-business',
    title: { he: 'מה זה WhatsApp API ואיך הוא משדרג את העסק שלך?', en: 'What is WhatsApp API and How Does It Upgrade Your Business?' },
    description: { he: 'גלה איך WhatsApp API מאפשר לעסקים לתקשר עם לקוחות בצורה ישירה, אוטומטית ויעילה. כל היתרונות, הפתרונות והאפשרויות.', en: 'Discover how WhatsApp API enables businesses to communicate with customers directly and automatically. All the benefits and possibilities.' },
    seoTitle: { he: 'WhatsApp API ישראל | מדריך מלא 2026 + מחירים | Gambot', en: 'WhatsApp API Israel | Complete Guide 2026 + Pricing | Gambot' },
    metaDescription: { he: 'מדריך מקיף ל-WhatsApp API בישראל ✓ מחירים ✓ התקנה ✓ אוטומציה ✓ בוטים. למד איך לשדרג את העסק עם WhatsApp Business API', en: 'Complete guide to WhatsApp API in Israel ✓ Pricing ✓ Setup ✓ Automation ✓ Bots. Learn how to upgrade your business with WhatsApp Business API' },
    keywords: { he: 'whatsapp api, whatsapp api ישראל, וואטסאפ עסקי, בוט whatsapp, אוטומציה whatsapp', en: 'whatsapp api, whatsapp business api, whatsapp automation, whatsapp bot, whatsapp israel' },
    category: 'WhatsApp API',
    author: 'ניר סגס',
    publishedDate: '2025-08-05',
    image: '/blog/post1.jpg',
    readTime: 8,
  },
];

export function getPostBySlug(slug) {
  return BLOG_POSTS.find(p => p.slug === slug || p.slugEn === slug || String(p.id) === String(slug));
}

export function getPostById(id) {
  return BLOG_POSTS.find(p => String(p.id) === String(id));
}

export function getAllSlugs() {
  const params = [];
  BLOG_POSTS.forEach(p => {
    params.push({ id: String(p.id), slug: p.slug });
    if (p.slugEn && p.slugEn !== p.slug) {
      params.push({ id: String(p.id), slug: p.slugEn });
    }
  });
  return params;
}
